### ISSUE TITLE
.reverse, color, and form fields

### ISSUE THREAD

**Issue by jungshadow** [louderthanten/livewires#6]
First, this is a _fantastic_ project. I recommend it to every developer/UX person I know. Thank you, so much, for this!

Gushing aside, I was blocking out the flow for a rather complex form and, for visual aid, I was dropping the fields in different callout boxes, alternating between .subtle and .reverse. Because _normalize.scss sets the color property to inherit, the select boxes and any un-classed form fields were showing up blank (i.e. the text was white-on-white). To have .reverse work as intended out-of-the-box, I'm wondering if it would be appropriate, in this case, to change the reverse declaration to:

```scss
.reverse {
  @include font-smoothing(on);
  background:$text;
  color:$background;
  
  // input, select, et al...
  input, select {
    color:$text;
  }
}
```

Or to add a bare-bones .select-box (and other similar classes) in `_scss/7_theme/_forms.scss` at the outset to re-assign the appropriate text color. Happy to provide a PR to whatever you think would be most appropriate.

Cheers.
